// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
if (!process.env.DATABASE_URL) {
  try {
    // @ts-ignore
    await import("dotenv/config");
  } catch (e) {
    // dotenv is not needed if DATABASE_URL is already in the environment
  }
}

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
};
